### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by linyatis** [grupozap/ligeiro#2]
These first supported tools are really nice!

We could refactor this project to support the other main languages that we use, like Python, Java and Scala.
This would easier the adoption of our defined guidelines.

@thiagoandrade6 started something in the past specific for logs in java (https://github.com/VivaReal/VivaRealLogs/pull/1). If you agree, we could transfer it to this project.

What do you think?

**Comment by brennovich** [comment]
I think is too cumbersome to maintain multiple libraries targeted for different environments in the same code base. I'd rather create an other project where standards and integration tests for all implementations (golang, java, scala), then would be easy to see the adoption status of the standard and furthermore future changes in the standard.

**Comment by iamthiago** [comment]
I do agree with @brennovich and besides, I believe this "library", has been entirely removed.

**Comment by lferreira** [comment]
`linyatis commented on Dec 9, 2017` hahaha

**Comment by brennovich** [comment]
I've just resurrect the the post :)

Can someone close it?
